### ISSUE TITLE
chroma not working with code from previous exercise

### ISSUE THREAD

**Issue by stanleynguyen** [gophercises/recover_chroma#1] opened 2019-06-13 16:15 UTC
With the `responseWriter` implementation from the previous exercise, chroma seems to be competing to write with the root handler as well hence outputting responses like this
```
/* Background */ .chroma/* LineTableTD */ .chroma .lntd { #960050; background-color: #1e0010 } /* LineTableTD */ .chroma .lntd { #960050; background-color: #1e0010 } ss="p">};h1>Hello!</h1>"er interface"pan>7f7 ss="p">};h1>Hello!</h1>"er interface"pan>7f7f } f7f } overflow: auto; display: block; } ss="p">};h1>Hello!</h1>"er interface"pan>7f ss="p">};h1>Hello!</h1>"er interface"pan>7f7f } f7f } ss="p">};h1>Hello!</h1>"er interface"pan>7f7f } ss="p">};h1>Hello!</h1 ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>"< ss="p">};h1>Hello!</h1> ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>& ss="p">};h1>Hello!</h1> ss="p">};h1>Hello!</h1> ss="p">};h1>Hello!</h1>&# ss="p">};h1>Hello!</h1> ss="p">};h1>Hello!</h1> ss="p">};h1>Hello!</h1>&# ss="p">};h1>Hello!</h1> ss="p">};h1>Hello!</h1& ss="p">};h1>Hello!</h1 ss="p">};h1>Hello!</h1>& ss="p">};h1>Hello!</h1>&# ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>"< ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>&# ss="p">};h1>Hello!</h1>"< ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>"< ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>"er ss="p">};h1>Hello!</h1>"< ss="p">};h1>Hello!</h1& ss="p">};h1>Hello!</h1>&# ss="p">};h1>Hello!</h1 ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>"< ss="p">};h1>Hello!</h1> ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>"< ss="p">};h1>Hello!</h1>" ss="p">};h1>Hello!</h1>" ss="p">} ss="p">} ss="p">};h1>< ss="p">};h1&<< ss="p">};h1>< ss="p">}<< ss="p">};h1>Hello!&<< ss="p">};h1>Hello!&<< ss="p">};h1>Hello<< ss="p">};h1>Hell<< ss="p">};h1>Hello<< ss="p">};h1>Hello<< ss="p">};h1>Hello!<<< ss="p">};h1>Hell<< ss="p">};h1>Hello!<< ss="p">};h1>Hello!</h1&g<<< ss="p">};h1>Hello!</h1>"er inte< ss="p">}<< ss="p">};h1&< ss="p">};h1& ss="p">};< ss="p">}<< ss="p">};h1< ss="p">};< ss="p">};h1& ss="p">} ss="p">};h1>Hell ss="p">};<< ss="p">};h1 ss="p">} ss="p">};h1>Hel ss="p">} ss="p">};h1>Hello!< ss="p">}< ss="p">};h1>Hello!< ss="p">}<< ss="p">};h1 ss="p">} ss="p">};h1>Hel ss="p">} ss="p">};h1>Hello!< ss="p">}< ss="p">};h1>He ss="p">}<< ss="p">};h1 ss="p">} ss="p">};h1>Hel ss="p">} ss="p">};h1>Hello!</h1&g ss="p">}< ss="p">
```
Would you mind advising what the problem is and how we can make them work together?

**Comment by joncalhoun** [comment] 2019-07-02 17:58
Are you still experiencing this issue? If so, can you share your code? Is it the same code as one of the solutions? What page are you visiting to reproduce the issue?

Thanks!

**Comment by stanleynguyen** [comment] 2019-07-13 05:12
Hi @joncalhoun , below is the code that was having problem. Steps to reproduce is just to go to /panic then one of the source code file through the browser
```go
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"net/url"
	"os"
	"runtime/debug"
	"strconv"
	"strings"

	"github.com/alecthomas/chroma/formatters/html"
	"github.com/alecthomas/chroma/lexers"
	"github.com/alecthomas/chroma/styles"
)

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/debug/", sourceCodeHandler)
	mux.HandleFunc("/panic/", panicDemo)
	mux.HandleFunc("/panic-after/", panicAfterDemo)
	mux.HandleFunc("/", hello)
	log.Fatal(http.ListenAndServe(":3000", recoverMw(mux, true)))
}

func sourceCodeHandler(w http.ResponseWriter, r *http.Request) {
	f := r.FormValue("path")
	lineStr := r.FormValue("line")
	line, err := strconv.Atoi(lineStr)
	if err != nil {
		line = -1
	}
	file, err := os.Open(f)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	b := bytes.NewBuffer(nil)
	_, err = io.Copy(b, file)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	lines := [][2]int{}
	if line > 0 {
		lines = append(lines, [2]int{line, line})
	}
	lexer := lexers.Get("go")
	iterator, err := lexer.Tokenise(nil, b.String())
	style := styles.Get("monokai")
	if style == nil {
		style = styles.Fallback
	}
	formatter := html.New(html.TabWidth(2), html.WithLineNumbers(), html.LineNumbersInTable(), html.HighlightLines(lines))
	w.Header().Set("content-type", "text/html")
	formatter.Format(w, style, iterator)
}

func recoverMw(app http.Handler, dev bool) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if err := recover(); err != nil {
				log.Println(err)
				stack := debug.Stack()
				log.Println(string(stack))
				msgForHTML := ""
				if !dev {
					msgForHTML = "Something went wrong :("
				} else {
					msgForHTML = fmt.Sprintf("<h1>panic: %v</h1><pre>%v</pre>", err, makeLinks(string(stack)))
				}

				w.WriteHeader(http.StatusInternalServerError)
				fmt.Fprint(w, msgForHTML)
			}
		}()

		nw := &responseWriter{ResponseWriter: w}
		app.ServeHTTP(nw, r)
		nw.flush()
	}
}

type responseWriter struct {
	http.ResponseWriter
	writes [][]byte
	status int
}

func (rw *responseWriter) Write(b []byte) (int, error) {
	rw.writes = append(rw.writes, b)
	return len(b), nil
}

func (rw *responseWriter) WriteHeader(statusCode int) {
	rw.status = statusCode
}

func (rw *responseWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	h, ok := rw.ResponseWriter.(http.Hijacker)
	if !ok {
		return nil, nil, fmt.Errorf("the reponseWriter doesnt support Hijacker interface")
	}
	return h.Hijack()
}

func (rw *responseWriter) Flush() {
	flusher, ok := rw.ResponseWriter.(http.Flusher)
	if !ok {
		return
	}

	flusher.Flush()
}

func (rw *responseWriter) flush() error {
	if rw.status != 0 {
		rw.ResponseWriter.WriteHeader(rw.status)
	}

	for _, write := range rw.writes {
		_, err := rw.ResponseWriter.Write(write)
		if err != nil {
			return err
		}
	}

	return nil
}

func panicDemo(w http.ResponseWriter, r *http.Request) {
	funcThatPanics()
}

func panicAfterDemo(w http.ResponseWriter, r *http.Request) {
	fmt.Fprint(w, "<h1>Hello!</h1>")
	funcThatPanics()
}

func funcThatPanics() {
	panic("Oh no!")
}

func hello(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, "<h1>Hello!</h1>")
}

func makeLinks(stack string) string {
	lines := strings.Split(stack, "\n")
	file := ""
	for li, l := range lines {
		if len(l) == 0 || l[0] != '\t' {
			continue
		}
		for i, c := range l {
			if c == ':' {
				file = l[1:i]
				break
			}
		}
		var lineStr strings.Builder
		for i := len(file) + 2; i < len(l); i++ {
			if l[i] < '0' || l[i] > '9' {
				break
			}
			lineStr.WriteByte(l[i])
		}
		v := url.Values{}
		v.Set("path", file)
		v.Set("line", lineStr.String())
		lines[li] = "\t<a href=\"/debug/?" + v.Encode() + "\">" + file + ":" + lineStr.String() + "</a>" + l[len(file)+2+len(lineStr.String()):]
	}
	return strings.Join(lines, "\n")
}
```

**Comment by jackytck** [comment] 2020-03-01 07:02
This is caused by appending the original pointer to the `writes` slice. When the value pointed by it changed, the whole html code would be jiggled around, thus failed to render properly.

To solve this, I simply copy the bytes every time:
https://github.com/jackytck/gophercises/blob/c6d4a83ca9ea3d820344477d539cba92ff139401/ex15/main.go#L105-L106

**Comment by joncalhoun** [comment] 2023-01-20 18:06
I'm closing this for now, but will keep issues like this in mind when I redo the course in the future.

**Closed as completed by joncalhoun** 2023-01-20 18:06 UTC
